name: Build and Publish Single Package to GitHub Packages

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'

      # 1. Instalacja zależności z publicznego rejestru npm
      - name: Configure .npmrc for Public npm Registry
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc

      - name: Install Dependencies
        run: yarn install

      # 2. Skonfiguruj .npmrc do publikacji w GitHub Packages
      - name: Configure .npmrc for GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > .npmrc
          echo "@vega:registry=https://npm.pkg.github.com/" >> .npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3. Budowanie tylko paczki vega-scenegraph
      - name: Build vega-scenegraph Package
        run: |
          cd packages/vega-scenegraph
          yarn install
          yarn build

      - name: Setup .yarnrc.yml
        run: |
          yarn config set npmScopes.my-org.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.my-org.npmAlwaysAuth true
          yarn config set npmScopes.my-org.npmAuthToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 4. Publikacja paczki vega-scenegraph do GitHub Packages
      - name: Publish vega-scenegraph Package to GitHub Packages
        run: |
          cd packages/vega-scenegraph
          yarn publish --new-version 1.0.1 --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}