name: Build and Publish Package to GitHub Packages
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Umożliwia pisanie do GitHub Packages
      id-token: write
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Node 20.x
          uses: actions/setup-node@v2
          with:
            node-version: 20.x
            registry-url: 'https://npm.pkg.github.com'
        
        - name: Install
          run: yarn install
          
        - name: Install Canvas and XML dependencies
          run: sudo apt-get install -y libxml2-utils

        - name: Publish
          run: |
            yarn versionup --yes
            yarn release --yes
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}