name: Build and Publish Packages to GitHub Packages

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'

      # 1. Instalacja zależności z publicznego rejestru npm
      - name: Configure .npmrc for Public npm Registry
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc

      - name: Install Dependencies
        run: yarn install

      # 2. Dodanie namespace @vega i konfiguracja do publikacji
      - name: Configure .npmrc for GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > .npmrc
          echo "@vega:registry=https://npm.pkg.github.com/" >> .npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add @vega namespace to all packages
        run: |
          for pkg in packages/*/package.json; do
            jq '.name = "@vega/" + .name' $pkg > tmp.$$.json && mv tmp.$$.json $pkg
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3. Budowanie paczek
      - name: Build All Packages
        run: |
          yarn workspaces list  
          yarn workspace @vega/vega-scenegraph run build

      # 4. Automatyczne zatwierdzenie changelogów (jeśli są generowane)
      - name: Commit Changelog Updates
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "chore(release): update changelogs [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 5. Publikowanie paczek do GitHub Packages
      - name: Publish Packages to GitHub Packages
        run: |
          lerna version --conventional-commits --no-git-tag-version --no-verify --yes
          lerna publish from-package --no-private --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}